DROP DATABASE IF EXISTS scene;
CREATE DATABASE scene WITH ENCODING 'UTF8';

\c scene;

CREATE TABLE movies (
    id SERIAL PRIMARY KEY,
    photo TEXT,
    title VARCHAR(255) NOT NULL,
    genero VARCHAR(100),
    ano_lancamento INT,
    sinopse TEXT
);

INSERT INTO movies (photo, title, genero, ano_lancamento, sinopse) VALUES
('https://i.ytimg.com/vi/prqwyv8mz30/maxresdefault.jpg', 'Como Treinar o Seu Dragão', 'Fantasia, Aventura', 2025, 'Na ilha de Berk, um garoto viking chamado Soluço desafia a tradição ao fazer amizade com o dragão Banguela. No entanto, quando uma ameaça surge, a amizade de Soluço com Banguela se torna a chave para forjar um novo futuro.'),
('https://i.pinimg.com/736x/00/b0/7d/00b07da3ad4a4e1ec19b2ec32d307e63.jpg', 'Velozes e Furiosos 2', 'Ação, Crime', 2003, 'O ex-policial Brian Conner se muda de Los Angeles para Miami para recomeçar sua vida. Ele acaba se envolvendo em rachas na sua nova cidade com seu amigo Tej e Suki. Suas aventuras terminam quando ele é preso e faz um acordo com agentes do FBI. Brian tem a missão muito perigosa de prender um poderoso chefe do cartel das drogas.'),
('https://www.entrandonumafria.com.br/wp-content/uploads/2022/09/amulherrei-poster.jpg', 'A Mulher Rei', 'Ação, Aventura', 2022, 'Em 1800, o general Nanisca treina um grupo de mulheres guerreiras para proteger o reino africano de Dahomey de um inimigo estrangeiro.'),
('https://i.pinimg.com/736x/0b/9d/41/0b9d41e1533406a3a0c3cbd9700787f7.jpg', 'E Assim que Acaba', 'Romance, Drama', 2024, 'Lily Bloom decide começar uma nova vida em Boston e tentar abrir o seu próprio negócio. Como consequência de sua mudança de vida, Lily acredita que encontrou o amor verdadeiro com Ryle, um charmoso neurocirurgião. No entanto, as coisas se complicam quando um incidente doloroso desencadeia um trauma do passado e também, quando seu primeiro amor reaparece.'),
('https://image.tmdb.org/t/p/original/aiRESjcG3Vi3W9WAGgMJSjGX1HQ.jpg', 'A Casa Mostro', 'Terror, Animação', 2006, 'Nenhum adulto acredita quando três adolescentes falam que existe uma casa no bairro que é uma criatura perigosa. Com o Dia das Bruxas se aproximando, eles têm que descobrir uma forma de destruir a casa antes que ela faça mal a crianças inocentes.'),
('https://i.pinimg.com/1200x/b7/57/b4/b757b481456304a4774870348383fdbc.jpg', '10 Coisas que Odeio em Você', 'Comédia, Romance', 1999, 'Bianca Stratford é bonita e popular, mas não pode namorar antes que sua irmã mais velha encontre um namorado primeiro. O problema é que nenhum garoto consegue chegar perto da irmã, Kat Stratford. Para resolver a situação, um rapaz interessado em Bianca suborna um amigo com passado misterioso para sair com Kat e, quem sabe, tentar conquistá-la.');

INSERT INTO movies (photo, title, genero, ano_lancamento, sinopse) VALUES
('https://i.ytimg.com/vi/3IDeifYOCvM/maxresdefault.jpg', 'Como Perder um Homem em 10 Dias', 'Comédia, Romance', 2003, 'Ben é um publicitário que aposta com o chefe que faz qualquer mulher se apaixonar por ele em dez dias. Se conseguir, será o responsável por uma cobiçada campanha de diamantes. Andie é uma jornalista que, por causa de uma matéria, está decidida a infernizar a vida de qualquer homem que se aproximar. Os dois se conhecem em um bar e escolhem um ao outro como alvo de seus planos totalmente opostos.'),
('https://m.media-amazon.com/images/S/pv-target-images/245204f8facdce09da7ba0c45dc618c81af3c73fd91cad014274abfb461dd903.jpg', 'Rio', 'Infantil, Comédia', 2011, 'Capturada por contrabandistas de animais quando tinha acabado de nascer, a arara Blu nunca aprendeu a voar e vive uma vida domesticada feliz em Minnesota, nos Estados Unidos, com sua dona, Linda. Blu pensa que é a última arara de sua espécie. Mas quando descobrem que Jewel, uma fêmea, vive no Rio de Janeiro, Blu e Linda vão ao seu encontro. Os contrabandistas capturam Blu e Jewel, mas as aves escapam e começam uma aventura arriscada rumo à liberdade.'),
('https://m.media-amazon.com/images/M/MV5BNjkyMDU5ZWQtZDhkOC00ZWFjLWIyM2MtZWFhMDUzNjdlNzU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', 'Annabelle', 'Terror, Mistério', 2014, 'John Form acha que encontrou o presente ideal para sua esposa grávida, uma boneca vintage. No entanto, a alegria do casal não dura muito. Uma noite terrível, membros de uma seita satânica invadem a casa do casal em um ataque violento. Ao tentarem invocar um demônio, eles mancham a boneca de sangue, tornando-a receptora de uma entidade do mal.'),
('https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEi54VekDAMTChO6ZHqDpgSdV8vqTmGaVkw6O7-qgQ64s_uaMazERkc7VrUskwC59p3VLhMBJNXdyyfvNYlbKinnJZfmd-cy-rZP9i9IE1dnr28RZgS2pFfER-bGyVGjOg13JUgt3kRm5WE/s1000/a+princesa+e+o+sapo.png', 'A Princesa e o Sapo', 'Infantil, Musical', 2009, 'Trabalhadora e ambiciosa, Tiana sonha um dia abrir o seu próprio restaurante em Nova Orleans. Seus planos tomam um rumo diferente quando ela conhece o príncipe Naveen, que foi transformado em sapo pelo maldoso Dr. Facilier. Porém, o príncipe sapo tem esperanças de se tornar um humano novamente se Tiana beijá-lo.'),
('https://www.infoescola.com/wp-content/uploads/2010/10/bela-e-a-fera.jpg', 'A Bela e a Fera', 'Infantil, Musical', 1991, 'A jovem Bela está cansada da vida provinciana de uma pequena cidade francesa, onde vive também o galã Gastón que, apesar de derreter corações, não consegue conquistá-la com seu jeito grosseiro. Maurice, o pai de Bela, viaja para expor uma de suas invenções e acaba preso em um castelo onde vive uma temível Fera, que precisa encontrar o verdadeiro amor e ser correspondido para quebrar um feitiço e voltar a ser príncipe. Em troca da liberdade do pai, Bela aceita ficar presa no castelo para sempre.'),
('https://br.web.img3.acsta.net/medias/nmedia/18/89/67/23/20061404.jpg', 'Gato de Botas', 'Infantil, Aventura', 2011, 'Antes de conhecer Shrek e sua turma, Gato de Botas vive uma grande aventura ao lado de Humpty Dumpty e Kitty Pata Mansa. Dispostos a roubar os feijões mágicos do casal fora da lei Jack e Jill, o trio quer mesmo é conseguir a famosa gansa que bota ovos de ouro. Porém, algumas coisas não estavam nos planos, e Gato vai descobrir, meio atrasado, que tem um grande problema pela frente para conseguir limpar o que ficou para trás: a sua honra.'),
('https://br.web.img2.acsta.net/medias/nmedia/18/91/54/04/20150812.jpg', 'Shrek', 'Comédia, Fantasia', 2001, 'Um ogro tem sua vida invadida por personagens de contos de fadas que acabam com a tranquilidade de seu lar. Ele faz um acordo pra resgatar uma princesa.');